#!/bin/bash

# Based off of installer presented at:  http://www.linuxjournal.com/node/1005818

# cut the decompressed payload archive off of this script, then untar it into a
# temp directory.  Then run the installer script from the payload.  Finally
# clean up the temp directory.

echo ""
echo "Self Extracting Installer"
echo ""

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR
./installer

cd $CDIR
rm -rf $TMPDIR

exit 0

__ARCHIVE_BELOW__
